
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Додаткова сторінка</title>
  </head>
  <body bgcolor="#1ff">
    <?php
        include "../username.php";
    ?>
    <h1>Додаткові розділи</h1>
    <h2 id="history">Історія</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="math">Математика</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="ds">DataScience</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="lingv">Лінгвістика</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="bio">Біологія</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="geo">Географія</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="phis">Фізика</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="lat1">Quidquid discis - tibi discis</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="lit">Література</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="chem">Хімія</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="phil">Філософія</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
    <h2 id="lat2">Unum castigbis, centum emendibis</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus at urna condimentum. Ridiculus mus mauris vitae ultricies. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Vitae ultricies leo integer malesuada nunc vel. Non blandit massa enim nec dui nunc. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Laoreet suspendisse interdum consectetur libero id. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet porttitor eget dolor morbi non. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Dolor purus non enim praesent elementum facilisis. Nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ac tortor dignissim convallis aenean et. Diam maecenas ultricies mi eget. Mauris in aliquam sem fringilla ut morbi tincidunt augue. In fermentum et sollicitudin ac orci phasellus. Penatibus et magnis dis parturient montes. Pellentesque adipiscing commodo elit at imperdiet.</p>
  </body>
</html>
